Test-Murano-master4/Test_Murano_Denis_Bardakov/Models/EmployeeRepository.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;

namespace Test_Murano_Denis_Bardakov.Models
{
    public class EmployeeRepository : IRepository
    {
        private EmployeesContext db;
        public EmployeeRepository()
        {
            this.db = new EmployeesContext();
        }
        public List<Employees> GetEmployeesList()
        {
            return db.Employees.ToList();
        }
        public Employees GetEmployeeById(int? id)
        {
            return db.Employees.Find(id);
        }

        public void Create(Employees e)
        {
            db.Employees.Add(e);
        }

        public void Update(Employees e)
        {
            db.Entry(e).State = EntityState.Modified;
        }

        public void Delete(int id)
        {
            Employees emp = db.Employees.Find(id);
            if (emp != null)
                db.Employees.Remove(emp);
        }

        public void Save()
        {
            db.SaveChanges();
        }

        private bool disposed = false;

        public virtual void Dispose(bool disposing)
        {
            if (!this.disposed)
            {
                if (disposing)
                {
                    db.Dispose();
                }
            }
            this.disposed = true;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
    }
}

Test-Murano-master4/Test_Murano_Denis_Bardakov/Models/Employees.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Test_Murano_Denis_Bardakov.Models
{
    [Table("list_employees")]
    public class Employees
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Поле не может быть пустым")]
        [Display(Name = "Имя")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Поле не может быть пустым")]
        [StringLength(50, ErrorMessage = "Длина строки должна быть до 50 символов")]
        [Display(Name = "Должность")]
        public string Position { get; set; }

        [Required(ErrorMessage = "Поле не может быть пустым")]
        [Display(Name = "Статус")]
        public string Status { get; set; }

        [Required(ErrorMessage = "Поле не может быть пустым")]
        [DataType(DataType.Currency)]
        [Display(Name = "Зарплата")]
        public decimal Salary { get; set; }
    }
}

Test-Murano-master4/Test_Murano_Denis_Bardakov/Models/EmployeesContext.cs
using System.Data.Entity;

namespace Test_Murano_Denis_Bardakov.Models
{
    public class EmployeesContext : DbContext
    {
        public EmployeesContext(): base("EmployeesContextTest")
        {
            Database.SetInitializer<EmployeesContext>(
                new CreateDatabaseIfNotExists<EmployeesContext>());
        }
        public virtual DbSet<Employees> Employees { get; set; }
    }
}

Test-Murano-master4/Test_Murano_Denis_Bardakov/Models/IRepository.cs
using System;
using System.Collections.Generic;

namespace Test_Murano_Denis_Bardakov.Models
{
    public interface IRepository : IDisposable
    {
        List<Employees> GetEmployeesList();
        Employees GetEmployeeById(int? id);
        void Create(Employees item);
        void Update(Employees item);
        void Delete(int id);
        void Save();
    }
}

Test-Murano-master4/Test_Murano_Denis_Bardakov/Controllers/EmployeesController.cs
using PagedList;
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Test_Murano_Denis_Bardakov.Models;

namespace Test_Murano_Denis_Bardakov.Controllers
{
    public class EmployeesController : Controller
    {
        IRepository repo;

        public EmployeesController()
        {
            repo = new EmployeeRepository();
        }
        
        public EmployeesController(IRepository r)
        {
            repo = r;
        }

        public ActionResult SaveReport()
        {
            //Можно использовать LINQ
            /*var dataReport = from data in repo.GetEmployeesList()
                             orderby data.FullName
                             where data.Status.StartsWith("ак")
                             select new { data.FullName, data.Salary };*/

            var employeesList = repo.GetEmployeesList()
                                .Where(x => x.Status.StartsWith("ак"))
                                .OrderBy(x => x.FullName);

            ViewBag.FilePath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + @"\Отчет.txt";
            using (StreamWriter file = new StreamWriter(ViewBag.FilePath))
            {
                byte tax = 0;
                decimal totalSalary = 0;
                decimal totalSalaryMinusTaxes = 0;
                
                foreach (var e in employeesList)
                {
                    if (e.Salary < 10000)
                        tax = 10;
                    else if (e.Salary >= 10000 && e.Salary < 25000)
                        tax = 15;
                    else if (e.Salary >= 25000)
                        tax = 25;

                    decimal salaryMinusTaxes = e.Salary - (e.Salary * tax / 100);

                    file.WriteLine("Имя = {0}; зарплата = {1}; налог = {2}%; зарплата за вычетом налогов = {3}",
                                    e.FullName, e.Salary, tax, salaryMinusTaxes);

                    totalSalary += e.Salary;
                    totalSalaryMinusTaxes += salaryMinusTaxes;
                }
                file.WriteLine();
                file.WriteLine("Итого: зарплата = {0}; сумма налогов = {1}; зарплата за вычетом налогов = {2}",
                                    totalSalary, (totalSalary - totalSalaryMinusTaxes), totalSalaryMinusTaxes);
            }
            return View();
        }

        public ActionResult Index(string filter, int? page)
        {
            var employeesList = repo.GetEmployeesList().OrderBy(z => z.FullName).AsQueryable();
            
            if (filter == "активен")
            {
                employeesList = employeesList.Where(x => x.Status.StartsWith("ак"));
            }
            else if (filter == "не активен")
            {
                employeesList = employeesList.Where(x => x.Status.StartsWith("не"));
            }

            return View(employeesList.ToPagedList(page ?? 1, 7));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,FullName,Position,Status,Salary")] Employees employee)
        {
            try 
            {
                if (ModelState.IsValid)
                {
                    repo.Create(employee);
                    repo.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex);
                ViewData["CreateError"] = "Unable to create; view innerexception";
            }
            return View("Create");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employees employee = repo.GetEmployeeById(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id,FullName,Position,Status,Salary")] Employees employees)
        {
            if (ModelState.IsValid)
            {
                repo.Update(employees);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View(employees);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employees employee = repo.GetEmployeeById(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            repo.Delete(id);
            repo.Save();
            return RedirectToAction("Index");
        }
    }
}

Test-Murano-master4/Test_Murano_Denis_Bardakov/Views/Employees/Create.cshtml
@model Test_Murano_Denis_Bardakov.Models.Employees

@{
    ViewBag.Title = "Создать";
}

<h2>Создать</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Сотрудник</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Status", new List<SelectListItem>
                {
                    new SelectListItem { Text="активен", Value="активен"},
                    new SelectListItem { Text="не активен", Value="не активен"}
                },
                "Выберите статус", new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Возвратиться к списку сотрудников", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Test-Murano-master4/Test_Murano_Denis_Bardakov/Views/Employees/Delete.cshtml
@model Test_Murano_Denis_Bardakov.Models.Employees

@{
    ViewBag.Title = "Удалить";
}

<h2>Удаление</h2>

<h3>Вы уверены что хотите удалить данные сотрудника?</h3>
<div>
    <h4>Сотрудник</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Возвратиться к списку сотрудников", "Index")
        </div>
    }
</div>

Test-Murano-master4/Test_Murano_Denis_Bardakov/Views/Employees/Edit.cshtml
@model Test_Murano_Denis_Bardakov.Models.Employees

@{
    ViewBag.Title = "Редактирование";
}

<h2>Редактирование</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Сотрудник</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Status", new List<SelectListItem>
                {
                    new SelectListItem { Text="активен", Value="активен"},
                    new SelectListItem { Text="не активен", Value="не активен"}
                },
                new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Возвратиться к списку сотрудников", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Test-Murano-master4/Test_Murano_Denis_Bardakov/Views/Employees/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Test_Murano_Denis_Bardakov.Models.Employees>

@{
    ViewBag.Title = "Список сотрудников";
}

@using (Html.BeginForm("Index", "Employees", FormMethod.Get))
{
    <b> Фильтровать по cтатусу: </b>
    @Html.RadioButton("filter", "активен") <text>активен</text>
    @Html.RadioButton("filter", "не активен") <text>не активен</text>
    @Html.RadioButton("filter", "все", true) <text>все</text>
    <input type="submit" name="submit" value="Фильтровать" class="btn btn-sm btn-default" />
}

<h2>Список сотрудников компании</h2>

<table class="table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Salary)
        </th>
        <th>
            Действия
        </th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="5"> Нет подходящих сотрудников по указанному фильтру</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salary)
                </td>
                <td>
                    @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }, new { @class = "btn btn-xs btn-warning" }) |
                    @Html.ActionLink("Удалить", "Delete", new { id = item.Id }, new { @class = "btn btn-xs btn-danger" })
                </td>
            </tr>
        }
    }
</table>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, filter = Request.QueryString["filter"] }),
                    new PagedListRenderOptions { Display = PagedListDisplayMode.IfNeeded })

Test-Murano-master4/Test_Murano_Denis_Bardakov/Views/Employees/SaveReport.cshtml
@{
    ViewBag.Title = "Сохранить отчет";
}

<div class="text-center">
    <h2>Отчет сохранен по адресу: @ViewBag.FilePath</h2>

    <div>
        @Html.ActionLink("Возвратиться к списку сотрудников", "Index")
    </div>
</div>

Test-Murano-master4/Test_Murano_Denis_Bardakov/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Моя компания</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <meta name="description" content="list, employees" />
</head>
<body>

    <ul class="nav nav-tabs navbar-default navbar-fixed-top">

        <li>@Html.ActionLink("Главная", "Index", "Employees")</li>
        <li>@Html.ActionLink("Добавить нового", "Create", "Employees")</li>
        <li>@Html.ActionLink("Сохранить отчет", "SaveReport", "Employees")</li>
    </ul>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Denis Bardakov App</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>